#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

./vendor/bin/phpstan

if [ $? -ne 1 ]; then
    echo "Opa! deu ruim com o phpstan.";
    exit 0;
fi;

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$")

for FILE $STAGED_FILES
do
    ./vendor/bin/pint "${FILE}"
    git add "${FILE}"
done;

exit 0;
